---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabari-app
  labels:
    app: sabari-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabari-app
  template:
    metadata:
      labels:
        app: sabari-app
    spec:
      containers:
      - name: sabari-container
        image: 084086932810.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
